In [714]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [715]:
data = pd.read_csv("Student_performance_dataset.csv")
data.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

In [716]:
data.shape

(1000, 12)

In [717]:
data.columns

Index(['student_id', 'gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'previous_grade',
       'final_exam_score', 'final_grade'],
      dtype='object')

In [718]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [719]:
data.duplicated().sum()

np.int64(0)

In [720]:
data.isnull().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [721]:
data['parental_education'].value_counts()

parental_education
High School    356
Bachelors      308
Masters        184
PhD             50
Name: count, dtype: int64

In [722]:
data['parental_education'].unique()

array(['Bachelors', 'High School', nan, 'Masters', 'PhD'], dtype=object)

In [723]:
data['parental_education'].fillna(
    data['parental_education'].mode()[0],inplace=True
    )

In [724]:
data['parental_education'].value_counts()

parental_education
High School    458
Bachelors      308
Masters        184
PhD             50
Name: count, dtype: int64

In [725]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          1000 non-null   object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [726]:
data.describe()

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.570700,85.092300,6.799500,69.740900,83.543500
std,288.819436,1.478559,9.270685,1.203527,12.613425,10.341333
min,1.000000,0.500000,54.800000,3.200000,31.300000,46.800000
25%,250.750000,2.600000,78.800000,5.900000,61.000000,76.075000
50%,500.500000,3.600000,85.200000,6.800000,69.600000,83.800000
75%,750.250000,4.500000,91.900000,7.600000,78.400000,91.525000
max,1000.000000,8.100000,100.000000,10.000000,100.000000,100.000000

In [727]:
cat_col = [col for col in data.columns if data[col].dtype == 'object']
num_col = [col for col in data.columns if data[col].dtype != 'object']

print('Categorial columns:',cat_col)
print('Numerical columns:',num_col)

Categorial columns: ['gender', 'parental_education', 'internet_access', 'extracurricular_activities', 'part_time_job', 'final_grade']
Numerical columns: ['student_id', 'study_time_hours', 'attendance_percent', 'sleep_hours', 'previous_grade', 'final_exam_score']

###   Encoding : Label Encoding

In [728]:
data['gender'].value_counts()

gender
Female    510
Male      490
Name: count, dtype: int64

In [729]:
data['gender'] = data['gender'].map({'Female':0,'Male':1})

In [730]:
data['internet_access'].value_counts()

internet_access
Yes    854
No     146
Name: count, dtype: int64

In [731]:
data['internet_access'] = data['internet_access'].map({'Yes':1,'No':0})

In [732]:
data['extracurricular_activities'].value_counts()

extracurricular_activities
Yes    572
No     428
Name: count, dtype: int64

In [733]:
data['extracurricular_activities'] = data['extracurricular_activities'].map({'No':0,'Yes':1})

In [734]:
data['part_time_job'].value_counts()

part_time_job
No     684
Yes    316
Name: count, dtype: int64

In [735]:
data['part_time_job'] = data['part_time_job'].map({'No':0,'Yes':1})

In [736]:
data.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,1,4.0,98.0,6.5,Bachelors,1,1,0,76.9,100.0,A
1,2,0,6.3,100.0,5.7,High School,1,1,1,75.5,100.0,A
2,3,1,4.9,85.3,7.9,Bachelors,1,0,1,88.5,97.3,A
3,4,1,2.6,77.5,8.0,High School,1,1,0,85.1,83.8,B
4,5,1,2.2,89.6,4.6,Bachelors,1,0,1,61.8,68.3,D

### Encoding : One hot Encoding

In [737]:
data = pd.get_dummies(data,columns=['parental_education'])
data

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,parental_education_Bachelors,parental_education_High School,parental_education_Masters,parental_education_PhD
0,1,1,4.0,98.0,6.5,1,1,0,76.9,100.0,A,True,False,False,False
1,2,0,6.3,100.0,5.7,1,1,1,75.5,100.0,A,False,True,False,False
2,3,1,4.9,85.3,7.9,1,0,1,88.5,97.3,A,True,False,False,False
3,4,1,2.6,77.5,8.0,1,1,0,85.1,83.8,B,False,True,False,False
4,5,1,2.2,89.6,4.6,1,0,1,61.8,68.3,D,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,1,2.8,75.4,8.2,1,1,0,60.5,70.7,C,False,False,True,False
996,997,1,6.7,88.4,7.1,0,1,0,82.2,99.5,A,False,True,False,False
997,998,0,2.6,84.5,8.0,1,1,1,65.2,79.2,C,False,True,False,False
998,999,0,4.6,85.3,8.1,0,0,1,52.2,82.2,B,False,True,False,False
999,1000,1,3.9,77.4,6.1,1,0,0,45.4,70.4,C,False,False,True,False

In [738]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['final_grade'] = le.fit_transform(data['final_grade'])
data

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,parental_education_Bachelors,parental_education_High School,parental_education_Masters,parental_education_PhD
0,1,1,4.0,98.0,6.5,1,1,0,76.9,100.0,0,True,False,False,False
1,2,0,6.3,100.0,5.7,1,1,1,75.5,100.0,0,False,True,False,False
2,3,1,4.9,85.3,7.9,1,0,1,88.5,97.3,0,True,False,False,False
3,4,1,2.6,77.5,8.0,1,1,0,85.1,83.8,1,False,True,False,False
4,5,1,2.2,89.6,4.6,1,0,1,61.8,68.3,3,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,1,2.8,75.4,8.2,1,1,0,60.5,70.7,2,False,False,True,False
996,997,1,6.7,88.4,7.1,0,1,0,82.2,99.5,0,False,True,False,False
997,998,0,2.6,84.5,8.0,1,1,1,65.2,79.2,2,False,True,False,False
998,999,0,4.6,85.3,8.1,0,0,1,52.2,82.2,1,False,True,False,False
999,1000,1,3.9,77.4,6.1,1,0,0,45.4,70.4,2,False,False,True,False

In [739]:
data.astype(int)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,parental_education_Bachelors,parental_education_High School,parental_education_Masters,parental_education_PhD
0,1,1,4,98,6,1,1,0,76,100,0,1,0,0,0
1,2,0,6,100,5,1,1,1,75,100,0,0,1,0,0
2,3,1,4,85,7,1,0,1,88,97,0,1,0,0,0
3,4,1,2,77,8,1,1,0,85,83,1,0,1,0,0
4,5,1,2,89,4,1,0,1,61,68,3,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,1,2,75,8,1,1,0,60,70,2,0,0,1,0
996,997,1,6,88,7,0,1,0,82,99,0,0,1,0,0
997,998,0,2,84,8,1,1,1,65,79,2,0,1,0,0
998,999,0,4,85,8,0,0,1,52,82,1,0,1,0,0
999,1000,1,3,77,6,1,0,0,45,70,2,0,0,1,0

In [740]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
cols = ['gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'internet_access', 'extracurricular_activities',
       'part_time_job', 'previous_grade',
       'parental_education_Bachelors', 'parental_education_High School',
       'parental_education_Masters', 'parental_education_PhD']
data[cols] = ss.fit_transform(data[cols])
data[cols]

,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,parental_education_Bachelors,parental_education_High School,parental_education_Masters,parental_education_PhD
0,1.020204,0.290495,1.393010,-0.248976,0.413473,0.865015,-0.679697,0.567862,1.498917,-0.919249,-0.474858,-0.229416
1,-0.980196,1.846842,1.608852,-0.914022,0.413473,0.865015,1.471243,0.456813,-0.667148,1.087845,-0.474858,-0.229416
2,1.020204,0.899501,0.022415,0.914853,0.413473,-1.156049,1.471243,1.487977,1.498917,-0.919249,-0.474858,-0.229416
3,1.020204,-0.656846,-0.819368,0.997984,0.413473,0.865015,-0.679697,1.218288,-0.667148,1.087845,-0.474858,-0.229416
4,1.020204,-0.927515,0.486475,-1.828459,0.413473,-1.156049,1.471243,-0.629874,1.498917,-0.919249,-0.474858,-0.229416
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.020204,-0.521511,-1.046001,1.164245,0.413473,0.865015,-0.679697,-0.732991,-0.667148,-0.919249,2.105892,-0.229416
996,1.020204,2.117511,0.356970,0.249808,-2.418536,0.865015,-0.679697,0.988259,-0.667148,1.087845,-0.474858,-0.229416
997,-0.980196,-0.656846,-0.063922,0.997984,0.413473,0.865015,1.471243,-0.360185,-0.667148,1.087845,-0.474858,-0.229416
998,-0.980196,0.696499,0.022415,1.081114,-2.418536,-1.156049,1.471243,-1.391349,-0.667148,1.087845,-0.474858,-0.229416
999,1.020204,0.222828,-0.830160,-0.581499,0.413473,-1.156049,-0.679697,-1.930727,-0.667148,-0.919249,2.105892,-0.229416

In [741]:
X = data.drop('final_grade',axis = 1)
y = data['final_grade']

In [742]:
from sklearn.model_selection import train_test_split

In [743]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.20, random_state=42)

# Logistic Regression

In [744]:
from sklearn.linear_model import LogisticRegression

In [745]:
model = LogisticRegression()

In [746]:
model.fit(X_train,y_train)

LogisticRegression()

In [747]:
y_pred = model.predict(X_test)

In [748]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [749]:
accuracy_score(y_test,y_pred)

0.535

In [750]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.62      0.74      0.68        47
           1       0.51      0.59      0.55        73
           2       0.48      0.53      0.50        55
           3       0.00      0.00      0.00        23
           4       0.00      0.00      0.00         2

    accuracy                           0.54       200
   macro avg       0.32      0.37      0.35       200
weighted avg       0.47      0.54      0.50       200

# Naive Bayes

In [751]:
from sklearn.naive_bayes import GaussianNB

In [752]:
model_NB = GaussianNB()

In [753]:
model_NB.fit(X_train,y_train)

GaussianNB()

In [754]:
y_pred_NB = model_NB.predict(X_test)

In [755]:
accuracy_score(y_test,y_pred_NB)

0.91

In [756]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        47
           1       0.92      0.92      0.92        73
           2       0.89      0.89      0.89        55
           3       0.87      0.87      0.87        23
           4       0.00      0.00      0.00         2

    accuracy                           0.91       200
   macro avg       0.72      0.73      0.73       200
weighted avg       0.90      0.91      0.91       200

# Decision Tree

In [757]:
from sklearn.tree import DecisionTreeClassifier

In [758]:
model_Tree = DecisionTreeClassifier()

In [759]:
model_Tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [760]:
y_pred_Tree = model_Tree.predict(X_test)

In [761]:
accuracy_score(y_test,y_pred_Tree)

0.995

In [762]:
print(classification_report(y_test,y_pred_Tree))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        47
           1       1.00      1.00      1.00        73
           2       1.00      1.00      1.00        55
           3       0.96      1.00      0.98        23
           4       1.00      0.50      0.67         2

    accuracy                           0.99       200
   macro avg       0.99      0.90      0.93       200
weighted avg       1.00      0.99      0.99       200

# SVM

In [763]:
from sklearn.svm import SVC

In [764]:
model_svm = SVC(kernel = 'rbf')

In [765]:
model_svm.fit(X_train,y_train)

SVC()

In [766]:
y_pred_svm = model_svm.predict(X_test)

In [767]:
accuracy_score(y_test,y_pred_svm)

0.365

In [768]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        47
           1       0.36      1.00      0.53        73
           2       0.00      0.00      0.00        55
           3       0.00      0.00      0.00        23
           4       0.00      0.00      0.00         2

    accuracy                           0.36       200
   macro avg       0.07      0.20      0.11       200
weighted avg       0.13      0.36      0.20       200